### ISSUE TITLE
verification

### ISSUE THREAD

**Issue by kanzuka** [paragonie/blakechain#2]
Hello,

i'm having trouble with verification. i hope you will help.
what i want to do is keep retrospective data changes and verify them when necessary. but i have not succeeded yet.

i can describe it with a sample code as follows.

```php
<?php
$real = [
        'title' => 'Test Title',
        'body'  => 'Test Body',
    ];

    $histories = [
        [
            'title' => 'Test Title 1',
            'body'  => 'Test Body',
        ],

        [
            'title' => 'Test Title 1',
            'body'  => 'Test Body 1',
        ],

        [
            'title' => 'Test Title',
            'body'  => 'Test Body',
        ],
    ];

$chainA = new \ParagonIE\Blakechain\Blakechain();

collect( $histories )->each( function($item) use ($chainA) {
        $chainA->appendData( json_encode( $item ) );
 );

$chainB = new \ParagonIE\Blakechain\Blakechain(
        new \ParagonIE\Blakechain\Node( json_encode($real), $chainA->getLastNode()->getPrevHash() )
);

dd( $chainA->getLastNode()->getHash() == $chainB->getLastHash() );

```

i tried something like, but i was not successful. i know what i'm doing is wrong. But i did not know what to do at the point of verification. i'm blocked because there is not enough document.

**Comment by paragonie-scott** [comment]
You're comparing a chain of 3 nodes with a chain of 1. It's not going to have the same hash.

> But i did not know what to do at the point of verification. i'm blocked because there is not enough document.

See [Chronicle](https://github.com/paragonie/chronicle) for an implementation of Blakechain.

The point of verification is to iterate through an entire chain and throw exceptions if any blocks were inserted, removed, reordered, or updated after their commitment into the chain structure.

**Comment by kanzuka** [comment]
thank you for your help. i solved the problem.
